### ISSUE TITLE
request not authorized

### ISSUE THREAD

**Issue by jw3126** [Azure-Samples/storage-blobs-python-quickstart#11]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
If I run the example, I get
```
azure.common.AzureHttpError: This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:ae1b306b-e01c-004c-645d-fb3536000000
Time:2019-04-25T11:55:55.8180602Z</Message></Error>
```

**Comment by akki** [comment]
@jw3126 You probably are not giving the right key when [initializing the blob service](https://github.com/Azure-Samples/storage-blobs-python-quickstart/blob/af172a726dab9591d02a9082d5d879c6cb569cb5/example.py#L46).

**Comment by jw3126** [comment]
You are probably right :)
